### PR TITLE
Reddit and Stackoverflow

### PR DESCRIPTION
**Pull request by 7Dump**

### CODE REVIEW

**Comment by sclinede** [comment]
Hi. Thank you for your contribution!

How did you decide what profit comes from those metrics?
I mean, could you please provide some research that you made for that?

I want to take a look on some values for projects from different groups. For example, you can take projects from testing environment: 'multi_json', 'rake', 'scientist', 'dry-web', 'reifier' and so on.

**Comment by 7Dump** [comment]
Привет, сложно обьяснить это на английском, на русском напишу. Эти метрики помогают понять для пользователя(девелопера) насколько он может расчитывать на помощь и получение ответа сообщества по проекту, вот к примеру по гему rake за последний месяц было 32 вопроса из них решение было получено на 10-вопросов что означает только 31 процент вопросов получили ответы, так же можем судить по параметру "last_month_question_owner_reputation_avg": 87.81 вопросы задают в основном "новички". Так же есть статистика по реддит но она не такая интересная: Гем rake был упомянут 48 раз и ~100 человек участвовали в обсуждении этого гема - по реддиту здесь мы можем судить больше косвенно и добавлять эти значения к другим метрикам.

**Comment by sclinede** [comment]
Let's try in English, to get more people involved and understood, what we are doing here.
I understand what you're talking about, but. Let's be a bit more scientific.
We need to see actually (in numbers) where is good trend and where is not.
Just run your code for different (not only popular as ```rake```)  projects and take a look what data do we have.
Just prepare and post a little report here.
More metrics we have - more noise could come. So we need to be sure that if we add metric we really obtain new useful information.
WDYT?

**Comment by 7Dump** [comment]
Ok, I'll do it

**Comment by tonkonogov** [comment]
I think it would be nice to see something like an explicit "evaluation" call for the gem to perform feature engineering faster and aside from coding. The current call of `spec` can't be used without changes as it uses VCR.

**Comment by sclinede** [comment]
@tonkonogov Could you please provide an example usage of that?
Chances are we'll create separate Issue for that. Sounds interesting and goes along with current plans.

**Comment by tonkonogov** [comment]
Yep, I'll elaborate on this a little later. The general idea behind that is to provide a "framework" for the simplest semi-supervised clustering.

**Comment by 7Dump** [comment]
@sclinede Hi. There is a problem - for example gem ROM on rubygems called ROM but that would find information on stackoverflow need to look at the RОМ-RB

**Comment by sclinede** [comment]
Hi. Yes, I thought that we have exceptions table for that purpose. (Gem name is not equal to github repo name, too). Later we can extract them from description or smth like that (think of search terms or so). But for now lets think that we have exceptions table and we can store here most useful search alias for gem. WDYT?

**Comment by tonkonogov** [comment]
is there any WIP?

**Comment by 7Dump** [comment]
@tonkonogov temporary no more time for this

**Comment by tonkonogov** [comment]
ok, I'll try to take it over and make some qualifications for proposed metrics

**Comment by 7Dump** [comment]
@tonkonogov ok

**Comment by tonkonogov** [comment]
A little update just to be in tune.
I decided to start with the simplest feature - a number of questions on SO. The most obvious way to get it is `/search` method, but (1) response doesn't have a total number of questions (2) it looks **only** through the titles of questions (3) it returns only up to 100 entries in a single response. 
Another way is via `tags` method. The response contains the number of questions with a specified tag. Seems good enough, but I don't have (and I suppose, nobody had ever) a reliable source of tags for a specific gem. For example, I tried to fetch a tag equals to a gem name, but out of 200 reference projects only 44 had own tags of the same name. Even worse, several gems (like `language`, `split`, `anima`) produced false-positive results: >10k entries for each. Taking into account, that I need to specify too much "exception tags", I decided to abandon this way.
Now I returned to `/search`, but before assessment & tests I have to deal with API rate limit. Such gems like `rails`, `rake` have a way too much results. The naive fetcher would deplete any rate limit in no time, so I have to introduce a kind of threshold to a number of questions.

**Comment by sclinede** [comment]
Sounds very interesting @tonkonogov
If you would like to chat about any problems, you could reach me out on Twitter.

**Comment by tonkonogov** [comment]
First results - https://gist.github.com/tonkonogov/83b8f704aac266e53781398bfd89aea1

I compared three methods of fetching - by a tag name (described earlier), by a string in title, and by string + one of tags `ruby` or `ruby-on-rails` (I am aware of plans to use it not only for rails world, but will delay it). Turned out it was a good conjecture indeed. Also I marked all anomaly values and compared basic stats.

First things first - a rate of nonzero entries is near to 50%. The breakdown by classes evinces that it has an obvious trend - more popular project, more chance to have a question on SO. A proposed feature for classifier to consider (here and next - FTC).

Concerning a number of questions - I see a median number as a reliable stat, but I would propose to use it only for class A projects with a threshold ~20-30 questions. Need to double check it later. So, FTC too.

As you can see, `tag` and `search` fetching engender too much anomalies. Obviously, numbers couldn't be precise (because it would require to introduce NLP techniques), but `search+tags` produces the most robust data statistic for me.

The next stage is to try to introduce a rate of answered questions and quarter stats. Seems like the latter may be unreliable, as it is not recommended to get all questions. The total stat is at least representative, but based only on the latest data.

**Comment by likeath** [comment]
Few weeks ago I also work on StackOverflow fetcher, you may see what I get [here](https://github.com/likeath/ossert/commit/502686566263f6ff868ec1c6933f6efad3733a5e
).
In short: it uses search with tags, but fetch only total number of questions, not the questions itself. It counts total number of questions and percent of questions with at least one answer.

I think that we should combine our efforts about this, so I create a [issue](https://github.com/ossert/ossert/issues/7) about what StackOverflow metric should be used. Let us discuss it there :)

**Comment by tonkonogov** [comment]
@likeath Like your solution, but disagree with a way to fetch the data. However, check my results please, tags are a way too unpredictable. Search + disjunctive set of general tags provides more robust set of data without conspicuous anomalies. Also nonzero rate is higher in `search + tags`, than in `tags`. Not to mention the problems with (1) the fact that not every project has own tag (2) people could ignore the tag while creating the question (3) combination of tags (as you proposed ruby) will lead (but I didn't check) to a lower rate of nonzero entries (4) projects often have slightly changed tags in order to avoid collisions and NameExceptions is probably the only way to fix it. Considering it all together, I decided to leave the way with tags.
Anyway, `filter: total` exactly what I missed in the docs, though it doesn't affect my table stats for medians.

**Comment by likeath** [comment]
@tonkonogov, great research 👍 

One thing that bothered me about search – there are many questions that really not related to projects. As I understand, you use `title` param, so for example this [request](https://api.stackexchange.com/2.2/search/advanced?fromdate=1420070400&todate=1451606400&order=desc&sort=activity&title=multi_json&site=stackoverflow) for `multi_json` will return questions that not about that gem. There are only two such questions for this period, though :)

> people could ignore the tag while creating the question

Good point, but is this necessarily bad? Maybe if questioner put right tags he knows what he asks about, and such questions would be more precise as metric? I don't know, in my opinion there are always be some trade-offs.

>  combination of tags (as you proposed ruby) will lead (but I didn't check) to a lower rate of nonzero entries

Yes, it is, so this proposition is invalid.

BTW, how you suppose to choose general tags?

**Comment by tonkonogov** [comment]
Not really a research, just a little testifying of one of OP's features.

> BTW, how do you suppose to choose general tags?

I already did. `st` column contains result for search by title + one of the tags `ruby` or `ruby-on-rails` via `tagged` parameter. Yet I didn't publish my branch..

Thus, the search query is (skipping all other params) https://api.stackexchange.com/docs/search#order=desc&sort=activity&tagged=ruby;ruby-on-rails&intitle=multi_json&site=stackoverflow

> Good point, but is this necessarily bad?

Neither bad nor good, but it contributes to the general problem (misleading number of questions) - a question could concern the project, but it may not be projected in tags.

> Maybe if questioner put right tags he knows what he asks about, and such questions would be more precise as metric? I don't know, in my opinion there are always be some trade-offs.

You completely right here. Obviously it is impossible to get only related questions, at least because it looks through the titles only. At least Precise metric is pretty good now, though website search is more suitable to increase Recall metric. Hardly it would be ever reasonable to use a crawler instead of API calls. 

Talking about website, sometimes it is even impossible to tell apart by myself if the question is related to my query or not without more deep inquiry. That's why I decided to check three methods and to select **the most reliable** of them. Too bad that I can't confirm it with a clear numbers for Precision-Recall.

**Comment by likeath** [comment]
> I already did. st column contains result for search by title + one of the tags ruby or ruby-on-rails via tagged parameter

I mean, how you would choose tags for real project? Always add these two tags for every request?

> ...because it looks through the titles only

Looks like `q` param in `search/advanced` method allowed to search through all properties of question.

**Comment by tonkonogov** [comment]
> Looks like q param in search/advanced method allowed to search through all properties of question.

Gosh! Shame on me, I overlooked this page completely. I will use today and update my stats with new results.

**Comment by sclinede** [comment]
As far as I know, further development is in https://github.com/ossert/ossert/pull/8
So closing this for given reason.

**Pull request closed without merging**
